name = "InterfaceLimits"
uuid = "e431586a-0d4c-4f33-917e-c5f3a3b2c228"
authors = ["cbarrows <clayton.barrows@nrel.gov>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
PowerNetworkMatrices = "bed98974-b02a-5e2f-9fe0-a103f5c450dd"
PowerSystems = "bcd98974-b02a-5e2f-9ee0-a103f5c450dd"

[compat]
DataFrames = "1"
JuMP = "1"
PowerNetworkMatrices = "0.7.1"
PowerSystems = "2.1"
julia = "1"
